Welcome  here! 
My personal introduction. 
    My name is caoyi, I'm studying in the
njust. I'm glad that I can produce this w-
ebsite by myself. Thanks to teacher who l-
et me do this, I can have this chance. 
为了尽可能避免语法错误，我还是用汉语吧。其实我觉得
个人主页内容和个人简介会有重复的地方，所以我想说一
些个人想法。一个人的好坏，一个人究竟如何，自己所言
未必为实，故，我的人生由我来创造，我的好坏由他人去
诉说。我创，故我在!Wish you have a good time！
